/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelola_user;

import helper.bantuan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ilham
 */
public class kelolaUserUtama extends javax.swing.JInternalFrame {
    private final String user = "root";
    private final String pwd = "";
    private final String host = "localhost";
    private final String db = "db10118228penyewaanbarang";
    private String urlValue = "";
    /**
     * Creates new form frame_kelolaUser
     */
    public kelolaUserUtama() {
        initComponents();
        tampil_tabel("");
    }
    
    private void tampil_tabel(String str){
        try {
            DefaultTableModel model = (DefaultTableModel) TabelData.getModel();
            model.setRowCount(0);
            Class.forName("com.mysql.jdbc.Driver");
            urlValue = "jdbc:mysql://" + host + "/" + db + "?user=" + user + "&password=" + pwd;
            Connection conn = DriverManager.getConnection(urlValue);
            
            PreparedStatement pStatement = null;
            String like = "%" + str + "%";
            String sql1 = "select id_user, user.nama, cabang.nama, status from user inner join cabang on user.id_cabang = cabang.id_cabang where user.nama like ? and status != 'deleted'";
            pStatement = conn.prepareStatement(sql1);
            pStatement.setString(1, like);
            ResultSet rs = pStatement.executeQuery();
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_user"),
                    rs.getString("user.nama"),
                    rs.getString("status"),
                    rs.getString("cabang.nama")
                });
            }
            TabelData.setRowHeight(20);
            pStatement.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal, " + e.toString());
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtCari = new javax.swing.JTextField();
        TblCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TblLihat = new javax.swing.JButton();
        TblTambah = new javax.swing.JButton();
        TblEdit = new javax.swing.JButton();
        TblHapus = new javax.swing.JButton();
        TblRefresh = new javax.swing.JButton();

        setClosable(true);
        setTitle("Kelola User");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Kelola Data User");

        TblCari.setBackground(new java.awt.Color(0, 0, 0));
        TblCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblCari.setForeground(new java.awt.Color(255, 255, 255));
        TblCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baseline_person_search_white_18dp.png"))); // NOI18N
        TblCari.setText("Cari");
        TblCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblCariActionPerformed(evt);
            }
        });

        TabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID User", "Nama ", "Status", "Nama Cabang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelData);
        if (TabelData.getColumnModel().getColumnCount() > 0) {
            TabelData.getColumnModel().getColumn(0).setResizable(false);
            TabelData.getColumnModel().getColumn(1).setResizable(false);
            TabelData.getColumnModel().getColumn(1).setPreferredWidth(250);
            TabelData.getColumnModel().getColumn(2).setResizable(false);
            TabelData.getColumnModel().getColumn(2).setPreferredWidth(100);
            TabelData.getColumnModel().getColumn(3).setResizable(false);
            TabelData.getColumnModel().getColumn(3).setPreferredWidth(250);
        }

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1, 5, 10));

        TblLihat.setBackground(new java.awt.Color(0, 102, 153));
        TblLihat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblLihat.setForeground(new java.awt.Color(255, 255, 255));
        TblLihat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baseline_account_circle_white_18dp.png"))); // NOI18N
        TblLihat.setText("Lihat");
        TblLihat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        TblLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblLihatActionPerformed(evt);
            }
        });
        jPanel2.add(TblLihat);

        TblTambah.setBackground(new java.awt.Color(0, 102, 153));
        TblTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblTambah.setForeground(new java.awt.Color(255, 255, 255));
        TblTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baseline_add_circle_outline_white_18dp.png"))); // NOI18N
        TblTambah.setText("Tambah");
        TblTambah.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        TblTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblTambahActionPerformed(evt);
            }
        });
        jPanel2.add(TblTambah);

        TblEdit.setBackground(new java.awt.Color(0, 102, 153));
        TblEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblEdit.setForeground(new java.awt.Color(255, 255, 255));
        TblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baseline_create_white_18dp.png"))); // NOI18N
        TblEdit.setText("Edit");
        TblEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        TblEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblEditActionPerformed(evt);
            }
        });
        jPanel2.add(TblEdit);

        TblHapus.setBackground(new java.awt.Color(0, 102, 153));
        TblHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblHapus.setForeground(new java.awt.Color(255, 255, 255));
        TblHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baseline_delete_white_18dp.png"))); // NOI18N
        TblHapus.setText("Hapus");
        TblHapus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        TblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblHapusActionPerformed(evt);
            }
        });
        jPanel2.add(TblHapus);

        TblRefresh.setBackground(new java.awt.Color(0, 102, 153));
        TblRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TblRefresh.setForeground(new java.awt.Color(255, 255, 255));
        TblRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baseline_refresh_white_18dp.png"))); // NOI18N
        TblRefresh.setText("Refresh");
        TblRefresh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        TblRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TblRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(TblRefresh);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TblCari, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TblCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        classKelolaUser.set_tampil(false);
    }//GEN-LAST:event_formInternalFrameClosed

    private void TblCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblCariActionPerformed
        // TODO add your handling code here:
        classKelolaUser.set_cari(TxtCari.getText());
        tampil_tabel(classKelolaUser.get_cari());
    }//GEN-LAST:event_TblCariActionPerformed

    private void TblLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblLihatActionPerformed
        // TODO add your handling code here:
        boolean buka = classKelolaUser.get_tampilPilihan();
        
        if(!buka && classKelolaUser.get_idTabel()!= 0){
            kelolaUserLihat KUL = new kelolaUserLihat();
            JDesktopPane panelUtama = getDesktopPane();
            bantuan.tampil(panelUtama, KUL, panelUtama.getSize());
            classKelolaUser.set_tampilPilihan(true);
        }else if(classKelolaUser.get_idTabel() == 0){
            JOptionPane.showMessageDialog(this, "Harap pilih salah 1 kolom yang ingin dilihat datanya");
        }
    }//GEN-LAST:event_TblLihatActionPerformed

    private void TabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataMouseClicked
        // TODO add your handling code here:
        int i = TabelData.getSelectedRow();
        TableModel tm = TabelData.getModel();

        int id = (int) tm.getValueAt(i, 0);
        classKelolaUser.set_idTabel(id);
        classHapusUser.set_id(id);
    }//GEN-LAST:event_TabelDataMouseClicked

    private void TblRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblRefreshActionPerformed
        // TODO add your handling code here:
        TxtCari.setText("");
        classKelolaUser.set_idTabel(0);
        tampil_tabel("");
    }//GEN-LAST:event_TblRefreshActionPerformed

    private void TblTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblTambahActionPerformed
        // TODO add your handling code here:
        boolean buka = classKelolaUser.get_tampilPilihan();
        
        if(!buka){
            kelolaUserTambah KUT = new kelolaUserTambah();
            JDesktopPane panelUtama = getDesktopPane();
            bantuan.tampil(panelUtama, KUT, panelUtama.getSize());
            classKelolaUser.set_tampilPilihan(true);
        }
    }//GEN-LAST:event_TblTambahActionPerformed

    private void TblEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblEditActionPerformed
        // TODO add your handling code here:
        boolean buka = classKelolaUser.get_tampilPilihan();
        
        if(!buka && classKelolaUser.get_idTabel()!= 0){
            kelolaUserEdit KUE = new kelolaUserEdit();
            JDesktopPane panelUtama = getDesktopPane();
            bantuan.tampil(panelUtama, KUE, panelUtama.getSize());
            classKelolaUser.set_tampilPilihan(true);
        }else if(classKelolaUser.get_idTabel() == 0){
            JOptionPane.showMessageDialog(this, "Harap pilih salah 1 kolom yang ingin dilihat datanya");
        }
    }//GEN-LAST:event_TblEditActionPerformed

    private void TblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TblHapusActionPerformed
        // TODO add your handling code here:
        boolean buka = classKelolaUser.get_tampilPilihan();
        if(!buka && classKelolaUser.get_idTabel()!= 0){
            int input = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus user dengan id " + Integer.valueOf(classHapusUser.get_id()) + "?", "Peringatan", JOptionPane.YES_NO_OPTION);
            if(input == 0){
                boolean hapus = classHapusUser.hapus_user();
                if(hapus){
                    tampil_tabel(classKelolaUser.get_cari());
                }else{
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data ini");
                }
            }
        }
    }//GEN-LAST:event_TblHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelData;
    private javax.swing.JButton TblCari;
    private javax.swing.JButton TblEdit;
    private javax.swing.JButton TblHapus;
    private javax.swing.JButton TblLihat;
    private javax.swing.JButton TblRefresh;
    private javax.swing.JButton TblTambah;
    private javax.swing.JTextField TxtCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
