/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelola_user;

import javax.swing.JOptionPane;

/**
 *
 * @author ilham
 */
public class kelolaUserEdit extends javax.swing.JInternalFrame {
    int id = 0;
    String username_lama = "";
    String password_lama = "";
    String alamat_lama = "";
    String cabang_lama = "";
    String kontak_lama = "";
    String nama_lama = "";
    String lahir_lama = "";
    String status_lama = "";
    
    /**
     * Creates new form kelolaUserEdit
     */
    public kelolaUserEdit() {
        initComponents();
        id = classKelolaUser.get_idTabel();
        classBacaUser.baca_data(id);
        classEditUser.set_id(id);
        
        username_lama = classBacaUser.get_username();
        password_lama = classBacaUser.get_password();
        alamat_lama = classBacaUser.get_alamat();
        cabang_lama = classBacaUser.get_cabang();
        kontak_lama = classBacaUser.get_kontak();
        nama_lama = classBacaUser.get_nama();
        lahir_lama = Integer.toString(classBacaUser.get_thn()) + "-" + Integer.toString(classBacaUser.get_bln()) + "-" + Integer.toString(classBacaUser.get_tgl());
        status_lama = classBacaUser.get_status();
        
        TxtUser.setText(username_lama);
        TxtPassword.setText(password_lama);
        TxtAlamat.setText(alamat_lama);
        TxtCabang.setText(cabang_lama);
        TxtKontak.setText(kontak_lama);
        TxtNama.setText(nama_lama);
        if(status_lama.equals("admin")){
            PbAdmin.setSelected(true);
        }else{
            PbPegawai.setSelected(true);
        }
        spinTgl.setValue(classBacaUser.get_tgl());
        spinBln.setValue(classBacaUser.get_bln());
        spinThn.setValue(classBacaUser.get_thn());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtNama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtKontak = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnSimpan = new javax.swing.JButton();
        TxtAlamat = new javax.swing.JTextField();
        spinThn = new com.toedter.calendar.JYearChooser();
        PbAdmin = new javax.swing.JRadioButton();
        PbPegawai = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        TxtCabang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spinTgl = new javax.swing.JSpinner();
        spinBln = new javax.swing.JSpinner();

        setClosable(true);
        setTitle("Edit Data User");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel3.setText("Username");

        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel4.setText("Password");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel1.setText("Nama User");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel8.setText("Tanggal Lahir (Tanggal - Bulan - Tahun)");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel6.setText("Alamat");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel7.setText("Kontak");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel5.setText("Status");

        BtnSimpan.setBackground(new java.awt.Color(0, 102, 153));
        BtnSimpan.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        BtnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        BtnSimpan.setText("Simpan");
        BtnSimpan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        PbAdmin.setText("Admin");
        PbAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PbAdminActionPerformed(evt);
            }
        });

        PbPegawai.setText("Pegawai");
        PbPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PbPegawaiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel9.setText("Nama Cabang");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel2.setText("-");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel10.setText("-");

        spinTgl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        spinBln.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtUser)
                    .addComponent(TxtPassword)
                    .addComponent(TxtNama)
                    .addComponent(TxtKontak, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtAlamat)
                    .addComponent(TxtCabang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PbAdmin)
                                .addGap(18, 18, 18)
                                .addComponent(PbPegawai))
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(spinTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinBln, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinThn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 337, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinBln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PbAdmin)
                    .addComponent(PbPegawai))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCabang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(BtnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUserActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        // TODO add your handling code here:
        String username = TxtUser.getText();
        String password = TxtPassword.getText();
        String nama = TxtNama.getText();
        String alamat = TxtAlamat.getText();
        String kontak = TxtKontak.getText();
        String cabang = TxtCabang.getText();
        String status = "";
        if(PbAdmin.isSelected()){
            status = "admin";
        }else if(PbPegawai.isSelected()){
            status = "pegawai";
        }else{
            status = "";
        }
        String tgl = Integer.toString((int)spinTgl.getValue());
        String bln = Integer.toString((int)spinBln.getValue());
        String thn = Integer.toString((int)spinThn.getValue());
        String lahir = thn+"-"+bln+"-"+tgl;
        JOptionPane.showMessageDialog(this, lahir + " = " + lahir_lama);
        if(username.equals(username_lama) && password.equals(password_lama) && nama.equals(nama_lama) && alamat.equals(alamat_lama) && kontak.equals(kontak_lama) && cabang.equals(cabang_lama) && status.equals(status_lama) && lahir.equals(lahir_lama)){
            JOptionPane.showMessageDialog(this, "Data masih sama dengan yang sebelumnya");
        }else if(!username.equals("") && !password.equals("") && !nama.equals("") && !alamat.equals("") && !kontak.equals("") && !cabang.equals("") && !status.equals("")){
            int input = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menyimpan perubahan ini? ", "Peringatan", JOptionPane.YES_NO_OPTION);
            if(input == 0){
                JOptionPane.showMessageDialog(this, "Tahap Awal");
                classEditUser.set_alamat(alamat);
                classEditUser.set_cabang(cabang);
                classEditUser.set_date(lahir);
                classEditUser.set_kontak(kontak);
                classEditUser.set_nama(nama);
                classEditUser.set_password(password);
                classEditUser.set_status(status);
                classEditUser.set_username(username);
                boolean cek_username = false;
                if(username.equals(username_lama)){
                    cek_username = true;
                }else{
                    cek_username = classEditUser.cek_username();
                }
                
                if(cek_username){
                    JOptionPane.showMessageDialog(this, "Username aman");
                    boolean cek_cabang = classEditUser.set_idcabang();
                    if(cek_cabang){
                        JOptionPane.showMessageDialog(this, "Cabang Aman");
                        boolean cek_updateUser = classEditUser.update_user();
                        if(cek_updateUser){
                            JOptionPane.showMessageDialog(this, "Berhasil menyimpan perubahan");
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(this, "Gagal menyimpan perubahan");
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Nama Cabang tidak dikenali");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Username sudah dipakai");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Harap mengisi semua kolom yang sudah tersedia!");
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void PbAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PbAdminActionPerformed
        // TODO add your handling code here:
        PbPegawai.setSelected(false);
    }//GEN-LAST:event_PbAdminActionPerformed

    private void PbPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PbPegawaiActionPerformed
        // TODO add your handling code here:
        PbAdmin.setSelected(false);
    }//GEN-LAST:event_PbPegawaiActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        classKelolaUser.set_tampilPilihan(false);
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JRadioButton PbAdmin;
    private javax.swing.JRadioButton PbPegawai;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtCabang;
    private javax.swing.JTextField TxtKontak;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spinBln;
    private javax.swing.JSpinner spinTgl;
    private com.toedter.calendar.JYearChooser spinThn;
    // End of variables declaration//GEN-END:variables
}
